#!/usr/bin/env python3

from app import app
from models import db, Destination, Activity, Review, DestinationActivity, TravelTip, User

with app.app_context():

    Destination.query.delete()
    Activity.query.delete()
    Review.query.delete()
    DestinationActivity.query.delete()
    TravelTip.query.delete()

    d1=Destination(name = "Banff National Park", location = "Canada", description = "A stunning alpine park in the Canadian Rockies known for turquoise lakes, glaciers, and rich biodiversity.", image_url = "https://themilepost.com/wp-content/uploads/2022/05/Peyto_Lake-Banff_NP-Canada.jpg")
    d2=Destination(name = "Costa Rica Cloud Forest", location = "Costa Rica", description = "A misty rainforest teeming with wildlife and rare orchids—perfect for birdwatching and canopy walks.", image_url = "https://landedtravel.com/wp-content/uploads/2020/02/Monteverde-Costa-Rica-Landed-Travel-Private-Travel.jpg")
    d3=Destination(name = "Sapa Rice Terraces", location = "Vietnam", description = "Scenic rice terraces nestled in the misty mountains, offering cultural treks and peaceful views.", image_url = "https://vietnamembassydelhi.in/wp-content/uploads/2023/06/Sapa-4-Easia_Travel-no-credit-needed.jpg")
    d4=Destination(name = "Masungi Georeserve", location = "Phillipines", description = "A conservation area with limestone peaks, rope courses, and a strong eco-tourism mission.", image_url = "https://i2.wp.com/www.awanderfulsole.com/wp-content/uploads/2017/07/IMG_20170225_094222.jpg?fit=1800%2C1335&ssl=1")
    d5=Destination(name = "Lofoten Islands", location = "Norway", description = "A dramatic archipelago above the Arctic Circle, ideal for kayaking, hiking, and witnessing the Northern Lights.", image_url = "https://res.cloudinary.com/simpleview/image/upload/v1454415126/clients/norway/Hamnoy_Lofoten_Norway_2_1_c0cf6de8-5b60-4571-b481-9729fab41d96.jpg")
    d6=Destination(name = "Lake Bled", location = "Slovenia", description = "A picturesque glacial lake with an island church and medieval castle, surrounded by forested trails.", image_url = "https://images.squarespace-cdn.com/content/v1/5aee2382f93fd4603e621996/1530883337137-72P1R42DRUHHKBMH7Y8O/Lake+Bled+Slovenia+DJI+Drone+Aerial+View.jpg")
    d7=Destination(name = "Jiuzhaigou Valley", location = "China", description = "A fairy-tale valley of multicolored lakes and waterfalls set in a UNESCO-listed nature reserve.", image_url = "https://upload.wikimedia.org/wikipedia/commons/2/28/1_jiuzhaigou_valley_wu_hua_hai_2011b.jpg")
    d8=Destination(name = "East Lake Cherry Blossom Park", location = "China", description = "A breathtaking cherry blossom park around East Lake—perfect for spring photography and peaceful strolls.", image_url = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/6c/c1/3f/east-lake-cherry-blossom.jpg?w=900&h=500&s=1")
    d9=Destination(name = "Kakadu National Park", location = "Australia", description = "A vast protected wilderness featuring wetlands, Aboriginal rock art, and incredible biodiversity.", image_url = "https://cuinthent.com/wp-content/uploads/2017/06/word-image.jpg")
    d10=Destination(name = "Salar de Uyuni", location = "Bolivia", description = "The largest salt flat, creating surreal mirrored landscapes during the rainy season.", image_url = "https://i.natgeofe.com/n/baead835-3391-4736-ad2c-defec78b7459/night-salar-de-uyuni-bolivia.jpg?w=1436&h=958")
    d11=Destination(name = "Reine", location = "Norway", description = "A quiet fishing village framed by dramatic fjords and colorful cabins—Norways Arctic gem.", image_url = "https://cdn.sanity.io/images/4aans0in/production/8ecabef5580df74492b50cfac06a8fe34dc6973f-2000x1335.jpg?rect=0,106,2000,1125&w=3840&h=2160&fm=webp&q=100&fit=max&auto=format")
    d12=Destination(name = "Azores Islands", location = "Portugal", description = "A group of volcanic islands in the mid-Atlantic known for crater lakes, hot springs, and whale watching.", image_url = "https://assets.vogue.com/photos/667edd6c9566b631889f8bd9/master/w_2560%2Cc_limit/GettyImages-1207075569.jpg")
    d13=Destination(name = "Raja Ampat", location = "Indonesia", description = "An untouched marine paradise with vibrant coral reefs, limestone islets, and top-tier diving.", image_url = "https://www.unesco.org/sites/default/files/2023-05/Raja_Ampat_UGGp_Karst_Wayag_cc_BKKPN_Kupang.JPG")
    d14=Destination(name = "Tsitsikamma National Park", location = "South Africa", description = "A lush coastal reserve with hiking trails, suspension bridges, and ocean views in the heart of the Garden Route.", image_url = "https://www.nature-reserve.co.za/images/tsitsikamma-national-park-beach-786x516.jpg")
    d15=Destination(name = "Bhutan", location = "Himalayas", description = "A Himalayan kingdom focused on sustainability and happiness, with monasteries perched on cliffs and pristine forests.", image_url = "https://good-nature-blog-uploads.s3.amazonaws.com/uploads/2022/04/Bhutan-mountain-1-2-1280x640.jpg")

    a1=Activity(name = "Hiking", category = "Land",sustainability_level = 5)
    a2=Activity(name = "Wildlife Watching", category = "Land", sustainability_level = 4)
    a3=Activity(name = "Bird Watching", category = "Land", sustainability_level = 5)
    a4=Activity(name = "Kayaking", category = "Water", sustainability_level = 4)
    a5=Activity(name = "Row Boating", category = "Water", sustainability_level = 5)
    a6=Activity(name = "Bungee Jumping", category = "Air", sustainability_level = 2)
    a7=Activity(name = "Nature Walk", category = "Land", sustainability_level = 4)
    a8=Activity(name = "Whale Watching", category = "Water", sustainability_level = 5)
    a9=Activity(name = "Coastal Hiking", category = "Land", sustainability_level = 5)
    a10=Activity(name = "Skygazing", category = "Air", sustainability_level = 5)
    a11=Activity(name = "Rock Climbing", category = "Land", sustainability_level = 4)
    a12=Activity(name = "Scuba Diving", category = "Water", sustainability_level = 5)
    a13=Activity(name = "Scenic Strolling", category = "Land", sustainability_level = 4)

    # Get user IDs for reviews
    kevin = User.query.filter_by(username='Kevin Kago').first()
    eddy = User.query.filter_by(username='Eddy Mwaniki').first()
    elvis = User.query.filter_by(username='Elvis Mungai').first()
    steve = User.query.filter_by(username='Steve Baars').first()
    godfrey = User.query.filter_by(username='Godfrey Makeri').first()
    abdullahi = User.query.filter_by(username='Abdullahi Abdikhadir').first()

    r1=Review(rating = 8, comment = "Incredible Views", user_id = kevin.id, destination_id = 6)
    r2=Review(rating = 10, comment = "Beautiful Skies", user_id = eddy.id, destination_id = 10)
    r3=Review(rating = 6, comment = "Great Hiking Experience", user_id = elvis.id, destination_id = 3)
    r4=Review(rating = 9, comment = "Amazing Beaches", user_id = steve.id, destination_id = 14)
    r5=Review(rating = 7, comment = "Wonderful Experience", user_id = godfrey.id, destination_id = 12)
    r6=Review(rating = 5, comment = "Delicious Food", user_id = abdullahi.id, destination_id = 8)

    da1=DestinationActivity(destination_id = 1, activity_id = 1, duration_minutes = 300)
    da2=DestinationActivity(destination_id = 2,activity_id = 7, duration_minutes = 180)
    da3=DestinationActivity(destination_id = 3,activity_id = 7,duration_minutes = 180)
    da4=DestinationActivity(destination_id = 3,activity_id = 1,duration_minutes = 300)
    da5=DestinationActivity(destination_id = 4,activity_id = 6,duration_minutes = 60)
    da6=DestinationActivity(destination_id = 5,activity_id = 4,duration_minutes = 30)
    da7=DestinationActivity(destination_id = 5,activity_id = 5,duration_minutes = 30)
    da8=DestinationActivity(destination_id = 6,activity_id = 4,duration_minutes = 30)
    da9=DestinationActivity(destination_id = 6,activity_id = 5,duration_minutes = 30)
    da10=DestinationActivity(destination_id = 7,activity_id = 5,duration_minutes = 30)
    da11=DestinationActivity(destination_id = 7,activity_id = 4,duration_minutes = 30)
    da12=DestinationActivity(destination_id = 8,activity_id =13,duration_minutes = 360)
    da13=DestinationActivity(destination_id = 9,activity_id = 1,duration_minutes = 300)
    da14=DestinationActivity(destination_id = 10,activity_id = 10,duration_minutes = 540)
    da15=DestinationActivity(destination_id= 11,activity_id = 10,duration_minutes = 540)
    da16=DestinationActivity(destination_id = 12,activity_id = 8,duration_minutes = 240)
    da17=DestinationActivity(destination_id = 13,activity_id = 12,duration_minutes = 60)
    da18=DestinationActivity(destination_id = 14,activity_id = 9,duration_minutes = 540)
    da19=DestinationActivity(destination_id = 14,activity_id = 5,duration_minutes = 30)
    da20=DestinationActivity(destination_id = 15,activity_id = 11,duration_minutes = 540)
    da21=DestinationActivity(destination_id = 2,activity_id = 3,duration_minutes = 120)
    da22=DestinationActivity(destination_id = 5,activity_id = 10,duration_minutes = 540)

    t1=TravelTip(tip = "Stick to designated trails in Banff to protect fragile alpine vegetation.", destination_id = 1)
    t2=TravelTip(tip = "Book eco-lodges or guided tours in Costa Rica that support cloud forest conservation.",destination_id = 2)
    t3=TravelTip(tip = "Support local farmers and avoid trampling rice paddies when exploring Sapa.",destination_id = 3)
    t4=TravelTip(tip = "Make a reservation in advance for Masungi Georeserve to avoid overcrowding and support preservation.", destination_id = 4)
    t5=TravelTip(tip = "Respect local wildlife and keep noise levels low while visiting Lofoten Islands.", destination_id = 5)
    t6=TravelTip(tip = "Avoid swimming in Lake Bled to preserve its delicate aquatic ecosystem.", destination_id = 6)
    t7=TravelTip(tip = "Use reusable water bottles and avoid littering in Jiuzhaigou Valley to maintain its pristine lakes.", destination_id = 7)
    t8=TravelTip(tip = "Visit East Lake Cherry Blossom Park during off-peak hours to reduce crowding impact on the flora.", destination_id = 8)
    t9=TravelTip(tip = "Respect Aboriginal culture in Kakadu and follow park rules to protect sacred sites.", destination_id = 9)
    t10=TravelTip(tip = "Leave no trace on the salt flats of Salar de Uyuni and avoid vehicle leaks or waste.", destination_id = 10)
    t11=TravelTip(tip = "Walk or bike around Reine instead of driving to minimize carbon emissions", destination_id = 11)
    t12=TravelTip(tip = "Choose whale-friendly boat operators in the Azores who follow safe viewing distances.", destination_id = 12)
    t13=TravelTip(tip = "Avoid stepping on coral reefs while diving in Raja Ampat to preserve marine biodiversity.", destination_id = 13)
    t14=TravelTip(tip = "Use boardwalks in Tsitsikamma to prevent erosion and avoid disturbing plant life.", destination_id = 14)
    t15=TravelTip(tip = "In Bhutan, respect the local customs and never litter in sacred or natural areas.", destination_id = 15)
    t16=TravelTip(tip = "Travel by shuttle or carpool to Banff to help reduce traffic congestion and pollution", destination_id = 1)
    t17=TravelTip(tip = "Pack biodegradable toiletries when visiting Costa Rica to avoid harming water sources.", destination_id = 2)

    db.session.add_all([d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15,a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13,r1, r2, r3, r4, r5, r6,da1, da2, da3, da4, da5, da6, da7, da8, da9, da10,da11, da12, da13, da14, da15, da16, da17, da18, da19, da20,da21,da22,t1, t2, t3, t4, t5, t6, t7, t8, t9, t10,t11, t12, t13, t14, t15, t16, t17])
    db.session.commit()
    print("Done seeding!")
